// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBf6wkV3rxxecOgVO97YyS3MO57_EFq-4',
    appId: '1:449463133541:web:52139190a23e4b7bc52d8c',
    messagingSenderId: '449463133541',
    projectId: 'idroapp-9f4e8',
    authDomain: 'idroapp-9f4e8.firebaseapp.com',
    storageBucket: 'idroapp-9f4e8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkk05on3cZnbE5TrvHlCloY7fKa0vkBgU',
    appId: '1:449463133541:android:22eab52482a267d1c52d8c',
    messagingSenderId: '449463133541',
    projectId: 'idroapp-9f4e8',
    storageBucket: 'idroapp-9f4e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtHttxf7dgQsndyC4HHiXXqZeRDR3JS2I',
    appId: '1:449463133541:ios:9b2d7c8b04f6cabdc52d8c',
    messagingSenderId: '449463133541',
    projectId: 'idroapp-9f4e8',
    storageBucket: 'idroapp-9f4e8.firebasestorage.app',
    iosBundleId: 'com.example.idroAppFinale',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtHttxf7dgQsndyC4HHiXXqZeRDR3JS2I',
    appId: '1:449463133541:ios:9b2d7c8b04f6cabdc52d8c',
    messagingSenderId: '449463133541',
    projectId: 'idroapp-9f4e8',
    storageBucket: 'idroapp-9f4e8.firebasestorage.app',
    iosBundleId: 'com.example.idroAppFinale',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBf6wkV3rxxecOgVO97YyS3MO57_EFq-4',
    appId: '1:449463133541:web:66b7cc1842f9c788c52d8c',
    messagingSenderId: '449463133541',
    projectId: 'idroapp-9f4e8',
    authDomain: 'idroapp-9f4e8.firebaseapp.com',
    storageBucket: 'idroapp-9f4e8.firebasestorage.app',
  );
}
